### ISSUE TITLE
Some deps missing in docs

### ISSUE THREAD

**Issue by Thaddy** [LongDirtyAnimAlf/Reiniero-fpcup#24]
The following dependencies under some clean Linux systems are missing:
(aptitude install)  libgtk2.0-dev libgdk-pixbuf2.0-dev libpango1.0-dev 

The system needs to be virgin, because any previous fpc/lazarus install by means of a package will have these dependencies resolved.

I guess this is a known and very old issue, because the above line is copied from an answer by BigChimp on the forum.Plz either add the above to readme.md or check for these and pull them in when missing.

**Comment by Thaddy** [comment]
What I mean: fpcup will fail with 512 when these are missing

**Comment by Thaddy** [comment]
What I mean: fpcup will fail with when these are missing. They are reported but not as dev versions. This is not clear for beginners, so better to add a line than create support issues ;)

**Comment by LongDirtyAnimAlf** [comment]
Done. Thanks !

**Comment by LongDirtyAnimAlf** [comment]
Just reverted library patch of yesterday, that was based on your remark.
Looking closer at the source, it seems to me that fpcup itself is checking the availability of these libraries !
(libX11.so,libgdk_pixbuf-2.0.so,libpango-1.0.so,libgdk-x11-2.0.so)
Could you please elaborate on your findings ?

**Comment by wkitty42** [comment]
@Thaddy : can you please elaborate on this?? i already have those installed on my kubuntu 14.04.4 but apparently there's still a problem with building the help...

**Comment by Thaddy** [comment]
A clean install on e.g. Raspbian (or a normal debian) is missing these dependencies even after you install build-essential.
This means that a clean fpcup first time run will always fail on debian.
Once you install fpc first through apt-get, these dependencies are resolved and after that there are never any problems (provided you do not run aopt-get autoremove)
Hence, these dependencies should be taken into account for fpcup.
Is this more clear? The problem is easily reproducable on virgin installs of debian based OS's.

**Comment by Thaddy** [comment]
@wkitty: you still always have to install sudo apt-get build-essential before running fpcup. Maybe even that can be resolved? ;)

**Comment by Thaddy** [comment]
@LongDirtyAnimAlf:
You can ONLY test this with virgin installs as per my remark. It fails (tested) on Raspbian and Debian Jessie and Wheezy on x86_64. I suspect it also fails on Ubuntu and Kubuntu.
It is reproducable every time. Just make sure you never install anything extra and run fpcup first.

**Comment by LongDirtyAnimAlf** [comment]
Ok. Thanks.
I have made some changes in the readme.
And made a beginning with the inclusion of distro specific help in fpcup itself.
I will extend this fpcup distro help in the future.
